### ISSUE TITLE
runSearchT uses strict State

### ISSUE THREAD

**Issue by Gurkenglas** [ennocramer/monad-dijkstra#1]
Therefore, infinite searches are impossible. Why?

**Comment by ennocramer** [comment]
Thanks for the report and for using this package.

`runSearchT` actually does use lazy State, but the choice of State monad should not affect the lazyness of the result.  Rather, I believe your problem stems from `IO`'s bind operator.  Sequencing a list of `IO` actions to produce a list of results in `IO` will never give you a lazy list. I.e. when using `runSearchT` as

    runSearchT :: (Ord c, Monoid c) => SearchT c IO a -> IO [(c, a)]

the list will not be lazy.  You need to use `collapse` from within your monadic computation to terminate the search.

I've updated the documentation and README to highlight this situation.

**Comment by Gurkenglas** [comment]
Here's a memory-diverging bottom without `IO` involved:

```
infinitesearch :: [(Sum Int, ())]
infinitesearch = runSearch go where
  go = pure () <|> cost' (Sum 1) >> go
```

**Comment by ennocramer** [comment]
I believe <|> binds tighter than >>, so that is an infinite recursion bottom for the first element of the resulting list. I.e. It's basically

  Inf = return () >> inf

But each recursion also spawns an alternative which needs to be thunked somewhere. I don't think there's any way to go about that differently, as runSearch needs to force the expression far enough to evaluate its cost, which stays at mempty and therefore is evaluated ever further. 

  Inf = return () <|> (cost' (Sum 1) >> Inf)

Works as expected and uses constant space when traversing the result list.

Cheers,
Enno

**Comment by Gurkenglas** [comment]
Yep, I realized that shortly after posting it, and deleted it, but apparently some sort of notification made it through to you. Sorry for the inconvenience!

**Comment by ennocramer** [comment]
No worries.  Your comment made me realize that I should add a unit test to verify the time/space complexity of runSearchT.
